### ISSUE TITLE
p2cor() doesn't handle very small pvalues

### ISSUE THREAD

**Issue by privefl** [tshmak/lassosum#11]
```
pval <- 10^-(0:500)
sign <- rnorm(length(pval))
lassosum::p2cor(pval, 10e3, sign)
```

**Comment by privefl** [comment]
ATM, I'm postprocessing with `cor <- ifelse(is.na(cor), max(abs(cor), na.rm = TRUE) * sign(gwas$estim), cor)`.

**Comment by tshmak** [comment]
`R` itself doesn't permit numbers closer than `.Machine$double.xmin` to zero, so `10^(-500)` is actually `0` in R. You may want to replace all your p-values less than `.Machine$double.xmin` to `.Machine$double.xmin` or some small numbers before running `p2cor`.

**Comment by privefl** [comment]
Yes, that is another solution.
You might want to include this directly in `p2cor()`.
