### ISSUE TITLE
explain the "pgs" in out

### ISSUE THREAD

**Issue by mjalbrzikowski** [tshmak/lassosum#13]
Hi thank you for making this software.  I'm trying it on my own data and I was wondering if you could explain what the out$pgs actually is.  I can see that rows are values for different individuals, but what are the columns in each "s"?
thank you
Maria

**Comment by tshmak** [comment]
The columns are for the different values of lambda, which is a tuning parameter used in lassosum (and lasso).

**Comment by mjalbrzikowski** [comment]
Thank you! If the column are the different values of lambda, what does "s" stand for?

**Comment by mjalbrzikowski** [comment]
Nevermind, I just read that "s" is a shrinkage parameter! thank you
Best
Maria
