### ISSUE TITLE
Support PLINK2 dosage format

### ISSUE THREAD

**Issue by wavefancy** [tshmak/lassosum#18]
Dear Developers,

Could you please help to support PLink2 dosage format? which probably better to guessing the missing genotype.

Best regards
Wallace

**Comment by tshmak** [comment]
That is too much engineering effort. I'm afraid I won't be able to do it.

**Comment by sariya** [comment]
This would be really really great. For example .gen from the IMPUTE2 software. There's a great information loss from .gen (IMPUTE2) --> PLINK format.
