### ISSUE TITLE
the link to the .tar.gz does not work

### ISSUE THREAD

**Issue by andgan** [tshmak/lassosum#2]
this link does not work: https://github.com/tshmak/lassosum/releases/download/v0.2.2/lassosum_0.2.2.tar.gz

**Comment by tshmak** [comment]
Fixed. Thanks for letting me know!

**Comment by andgan** [comment]
Great, thanks, you also mention that the Berisa.2015.EUR.bed is part of the package, but I couldn’t find the file.
Cheers,

**Comment by tshmak** [comment]
I think it should be available in the tutorial/data/ folder. Is this folder not available?

**Comment by andgan** [comment]
Found it , thanks!
