### ISSUE TITLE
Lassosum standalone error

### ISSUE THREAD

**Issue by dheerajbobbili1988** [tshmak/lassosum#21]
Hi,

I am trying to use lassosum in my pipeline and I'm getting the following error. Any help would be appreciated.

_Running lassosum.pipeline
Coordinating summary stats with reference panel...
Splitting genome by LD blocks ...
Running lassosum ...
s =  0.2
Error in serialize(data, node$con, xdr = FALSE) : ignoring SIGPIPE signal
Calls: do.call ... postNode -> sendData -> sendData.SOCK0node -> serialize
Execution halted_

Thank you

**Comment by tshmak** [comment]
That seems an error from the `parallel` package. I did a google search and [this](https://stackoverflow.com/questions/28503208/doparallel-error-in-r-error-in-serializedata-nodecon-error-writing-to-con) turns up. Perhaps try using fewer clusters to reduce memory?

**Comment by dheerajbobbili1988** [comment]
Thank you for your reply. It seems that there was a problem with my summary stats file as well. I excluded that particular file for now and it seems to work with other files that I have. 

I have another question regarding using a standalone version per chromosome. This is the command that I'm using to run the analysis per chromosome. 
lassosum --data <summary data for all chromosomes> --chr CHR --pos BP --A1 A1 --A2 A2 --pval P --n 50000 --beta OR --test.bfile <plink format bed file for single chromosome> --LDblocks EUR.hg19 --pheno <phenotype file> --nthreads 4 --out <output file>

It runs smoothly and as you described in the tutorial it generated the following files per chromosome

*.validate.results.txt
*.splitvalidate.results.txt
*.validate.rds
*.splitvalidate.rds
*.lassosum.pipeline.rds

Now, if I understand correctly I should use the *.splitvalidate.results.txt file. I apologize in case I misunderstood something but I have the following questions regarding the results.
1) Can I simply sum the PRS per chromosome for each individual or is there is some scaling that needs to be performed in order to proceed with the downstream analysis?
2) How can I get the list of SNPs that were used to generate the best performing PRS?
3) How can I set a seed value in case I want to obtain the same results everytime?

Look forward to your response.

**Comment by tshmak** [comment]
Hi, sorry for the late reply. 
1. It's best to use the `merge` command in lassosum. Simply use the `readRDS()` function in `R` to read the `*.lassosum.pipeline.rds` files, and run `merge` as in [here](https://cran.r-project.org/src/contrib/minqa_1.2.4.tar.gz). If it is too much trouble, yes, I think simply summing them across the chromosomes also works. 
2. After you've done the merge, there should be a `$sumstats` object in the merged object. It should give you all the SNPs that you used. 
3. Let me see...

**Comment by tshmak** [comment]
3. It seems it wasn't possible at the moment, but I've just added the option now. You can specify the seed with `--seed`. In fact, I've now defaulted the seed to 1234, so it will give deterministic results even if no seed is specified.

**Comment by dheerajbobbili1988** [comment]
Thank you for your help and clarification. The seed options works now.

**Comment by dheerajbobbili1988** [comment]
I have split my analysis per chromosome as I mentioned earlier and merged the ```*.lassosum.pipeline.rds``` file as per your suggestion . However, according to the issue here [](https://github.com/tshmak/lassosum/issues/8) I cannot use validate or splitvalidate results per chromosome directly. Has it changed since then, could you please clarify? In case I need to run a second round of validate and splitvalidate on the merged dataset could you please let me know how to do that using the standalone version of lassosum. Because here [](https://github.com/tshmak/lassosum/blob/master/lassosum_standalone.md) it says how to use validate on a new dataset but not on the same dataset.

Please let me know in case I misunderstood something?

**Comment by tshmak** [comment]
Technically you *can* validate/splitvalidate with one chromosome only. In the usual application of PGS, the PGS is generated for the entire genome and not just one chromosome, hence the assumed pipeline is to merge first. If you do want it for just one chromosome, it also makes sense to merge first and then validate/splitvalidate, since it may be better to have a single `(s, lambda)` for the entire genome. To get a PGS for just one chromosome, you can get the appropriate betas from the `$sumstats` in the `lassosum.pipeline` object and calculate the PGS just for that particular chromosome.
