### ISSUE TITLE
Speed up lassosum

### ISSUE THREAD

**Issue by dheerajbobbili1988** [tshmak/lassosum#25]
Hi,

I calculated the PRS using internal dataset (whole dataset )and now trying to use UK biobank as a validation dataset (per chromosome). I used the command below, the analysis is running without any error. However it is taking too long to compute the new PGS. It is stuck at the "Calculating PGS" step for almost 3 days. Is it normal? and is there a way to speedup? I am using the standalone version of lassosum.

```lassosum --lassosum.pipeline <internal.lassosum.pipeline.rds> --validate.rds <internal.validate.rds> --applyto ukb_chr --out ukb_chr1 --nthreads 16```

Please let me know if something is unclear.

Regards

**Comment by tshmak** [comment]
Hi dheeraj, 

Thanks for letting me know. I think there is currently a bug that causes lassosum standalone to ignore the --nthreads options. I've now made a fix and will release v0.4.5 in a few hours which will include this fix and other bug fixes. Please try and let me know if it works. 

Thanks, 
Tim

**Comment by dheerajbobbili1988** [comment]
Hi Tim,

Yes, it works now. Sorry for not getting back to you earlier.

Thanks,
