### ISSUE TITLE
what is the format of the LDfile used in ?

### ISSUE THREAD

**Issue by sariya** [tshmak/lassosum#26]
I installed lassosum library on Rv4.0, `~/libraries_R/R_LIB4.0/lassosum/data` where I've following files:
```

list.files()
 [1] "Berisa.AFR.hg19.bed"  "Berisa.AFR.hg38.bed"  "Berisa.ASN.hg19.bed"
 [4] "Berisa.ASN.hg38.bed"  "Berisa.EUR.hg19.bed"  "Berisa.EUR.hg38.bed"
 [7] "Berisa.R"             "Berisa.README"        "GenerateData.R"
[10] "refpanel.bed"         "refpanel.bim"         "refpanel.fam"
[13] "summarystats.txt"     "testsample.bed"       "testsample.bim"
[16] "testsample.covar.txt" "testsample.fam"       "testsample.pheno.txt"

```
I've data for an admixed population for which none of the widely used population or LD panel will be helpful. 
What is the format of LD used in pipeline with the `lassosum.pipeline` function?

```
### Read LD region file ###
LDblocks <- "EUR.hg19" # This will use LD regions as defined in Berisa and Pickrell (2015) for the European population and the hg19 genome.
# Other alternatives available. Type ?lassosum.pipeline for more details. 
```

I think from the `?lassosum.pipeline` LD block is a data.frame of the following format:

```
chr	start	stop
chr1	1961168	3666172

```

I'm at the repo https://bitbucket.org/nygcresearch/ldetect/src/master/ 
Can this be used to create an in-house LD acceptable data format for the lassosum? 
I got link to this code repository from https://academic.oup.com/bioinformatics/article/32/2/283/1743626

Or, can output from plink be used? https://zzz.bwh.harvard.edu/plink/ld.shtml
`plink --file mydata --r`

thanks,

**Comment by tshmak** [comment]
It's the BED format, as detailed [here](https://genome.ucsc.edu/FAQ/FAQformat.html#format1). You can have a look at the file "Berisa.EUR.hg19.bed" for reference.

**Comment by sariya** [comment]
thank you. I've an admixed population and I'd like create the bed regions for the population for which I'm interested to use `lassosum`. I was unable to find any guidelines to work with an in-house population data specifically `LDblocks`

`out <- lassosum.pipeline(cor=cor, chr=ss$Chr, pos=ss$Position, A1=ss$A1, A2=ss$A2, ref.bfile=ref.bfile, test.bfile=test.bfile,                           LDblocks = LDblocks).`

**Comment by tshmak** [comment]
Deriving an appropriate set of LD blocks is beyond the scope of lassosum. You could refer to the Berisa and Pickrell paper or their codes if you want to run their algorithm on your data. Or you can try some other software. My experience with Berisa and Pickrell was that it was not easy to run. 

However, if PGS is your aim, my simulations suggested that these LD block boundaries don't actually matter all that much. Just use, say, the EUR LD blocks, and I think you'll get results that are close to optimum.

**Comment by sariya** [comment]
Thanks for your reply. Based on my limited understanding and I could be wrong LD patterns and blocks are population specific. In the interested population they have smaller LD blocks and stronger SNP correlation than the EUR. It's a three-way admixed population.
