### ISSUE TITLE
About installing the package

### ISSUE THREAD

**Issue by felixhu93** [tshmak/lassosum#30]
Hi,
After I install the package into R and use library(lassosum), it says:

Error: package or namespace load failed for ‘lassosum’ in get(Info[i, 1], envir = env):
 lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/lassosum/R/lassosum.rdb' is corrupt
In addition: Warning message:
In get(Info[i, 1], envir = env) : internal error -3 in R_decompress1

And I find when I try to install it, it says:

functions.cpp:424:9: warning: unused variable 'i' [-Wunused-variable]
  int j,i;
        ^
functions.cpp:467:7: warning: unused variable 'nreps' [-Wunused-variable]
  int nreps=startvec.n_elem;
      ^
2 warnings generated.
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o lassosum.so RcppExports.o functions.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/Cellar/gcc/10.2.0/lib/gcc/10 -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-lassosum/00new/lassosum/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (lassosum)

So I'm not sure whether I install the package correctly.

Thank you so much!

**Comment by privefl** [comment]
You probably need to restart all your R sessions and try reinstalling the package.

**Comment by felixhu93** [comment]
I edit the Makecof file and restart the R. Finally it works. Thx!
