### ISSUE TITLE
Error in `$<-.data.frame`(`*tmp*`, "ok123", value = TRUE) :    replacement has 1 row, data has 0

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [tshmak/lassosum#40]
I'm trying to run lassosum using the following code and I'm getting this error: Error in `$<-.data.frame`(`*tmp*`, "ok123", value = TRUE) : 
  replacement has 1 row, data has 0

out <- lassosum.pipeline(cor=cor, chr=ss$CHR, pos=ss$BP, 
                         A1=ss$A1, A2=ss$A2, # A2 is not required but advised
                         ref.bfile=ref.bfile, test.bfile=test.bfile, 
                         LDblocks = LDblocks)

#Log

Coordinating summary stats with reference panel...
Error in `$<-.data.frame`(`*tmp*`, "ok123", value = TRUE) : 
  replacement has 1 row, data has 0

Can you please suggest how to address this issue? TIA

**Comment by privefl** [comment]
Maybe provide some `str()` of `cor` and `ss`.

Or try to find the problematic line yourself using `debugonce(lassosum.pipeline)`.

**Comment by Mahantesh-Biradar** [comment]
Here you go:

> str(cor)
 num [1:20382] 0.0183 0.0198 0.0195 0.0185 0.0189 ...
> str(ss)
Classes ‘data.table’ and 'data.frame':	20382 obs. of  12 variables:
 $ SNP      : chr  "rs74491544" "rs11804831" "rs1268339" "rs3813208" ...
 $ CHR      : int  1 1 1 1 1 1 1 1 1 1 ...
 $ BP       : int  1187641 1194804 1215424 1261133 1279428 1297065 1299068 1299662 1299946 1300074 ...
 $ A1       : chr  "C" "T" "T" "G" ...
 $ A2       : chr  "T" "C" "C" "T" ...
 $ Z        : num  2.17 3.92 3.65 2.37 2.33 ...
 $ N        : int  59188 59188 59188 59188 59188 59188 59188 59188 59188 59188 ...
 $ FRQ      : num  0.928 0.808 0.783 0.907 0.899 ...
 $ beta: num  0.0367 0.026 0.0244 0.0328 0.0323 ...
 $ se  : num  0.00823 0.00539 0.00515 0.00729 0.00703 ...
 $ z   : num  4.46 4.83 4.74 4.49 4.6 ...
 $ pval: num  0.00000822 0.00000139 0.00000218 0.000007 0.00000423 ...
 - attr(*, ".internal.selfref")=<externalptr>
 
And I dont see anything if I enter debugonce(lassosum.pipeline)

Thanks

**Comment by privefl** [comment]
After running `debugonce(lassosum.pipeline)`, you need to rerun `lassosum.pipeline` -> it will run in debug mode.

I guess the error comes from this line:
https://github.com/tshmak/lassosum/blob/0e44b530c77e862f1b88f9e1fad88fdab44e7827/R/matchpos.R#L150

And seems to happen when you have a data.frame of 0 rows, e.g.
```r
df <- iris[0, ]
df$ok123 <- TRUE
```

It seems to mean that no variant is matched at all?

**Comment by Mahantesh-Biradar** [comment]
Any idea why this is happening? does the SNP matching is done using CHR and POS or SNP?

**Comment by privefl** [comment]
No idea. This is why you should rerun in debug mode line by line.

**Comment by Mahantesh-Biradar** [comment]
Thanks Florian, here is the result when I run debugonce(lassosum.pipeline)
![Screenshot 2022-09-27 212611](https://user-images.githubusercontent.com/7866207/192628518-6bf93b7b-4a44-495d-be17-4abf018b9402.jpg)

**Comment by privefl** [comment]
Yes, just run line by line (using 'Next').
When you see the `matchpos()` function, just go into it (the second button).

**Comment by Mahantesh-Biradar** [comment]
Hi Florian, I'm not sure if I'm doing it right. Following is the code which I see after pressing the second button as per your instructions. 
`function (test, target, default.targets, auto.detect = T, silent = F) 
{
  mustfind <- target != ""
  if (mustfind) {
    test2 <- test
    targets2 <- target
  }
  else if (auto.detect) {
    test2 <- tolower(substr(test, 1, 3))
    targets2 <- tolower(substr(default.targets, 1, 3))
    target <- default.targets[1]
  }
  else return(integer(0))
  pos <- test2 == targets2[1]
  if (length(targets2) > 1) {
    for (i in 2:length(targets2)) {
      pos <- pos | test2 == targets2[i]
    }
  }
  pos <- which(pos)
  if (length(pos) > 1) {
    vars <- paste(test[pos], collapse = ", ")
    mess <- paste0("Multiple columns for ", target, ". Possible matches: ", 
      vars)
    stop(mess)
  }
  else if (length(pos) == 1) {
    if (!silent) 
      cat(paste(test[pos], "identified as", target, "\n"))
  }
  else if (mustfind) {
    stop(paste("No column identified for ", target))
  }
  else {
    if (!silent) 
      cat("No column identified for ", target, "\n")
  }
  return(pos)
}
`

**Comment by tshmak** [comment]
The problem is when lassosum failed to merge (coordinate) your summary stats (ss) with your test.bfile and ref.bfile. So make sure they share the same chr/BP. Check all of these use the same reference genome. If you want to merge using rsID alone then perhaps just delete the CHR/BP info from the summary stats.

**Comment by Mahantesh-Biradar** [comment]
I found that both my sumstat and test data are on GRch37 build. So I changed LDblocks <- "EUR.hg19". However I still get the same error: Error in `$<-.data.frame`(`*tmp*`, "ok123", value = TRUE) : 
  replacement has 1 row, data has 0
  
  If I want to match the using rsID and then what changes I have to make in the following piece of code apart from dropping CHR and POS in the summary stats?

  out <- lassosum.pipeline(cor=cor, chr=ss$CHR, pos=ss$BP,
A1=ss$A1, A2=ss$A2, # A2 is not required but advised
ref.bfile=ref.bfile, test.bfile=test.bfile,
LDblocks = LDblocks)

**Comment by tshmak** [comment]
What about the `ref.bfile`? That has to match as well. Also, it's best to examine the `.bim` files to see that the CHR/BP actually match those in the summary stats. If they don't match and you decide to use rsID only, again you need to make sure that these match in the .bim files. To use rsIDs, just replace `chr=ss$CHR, pos=ss$BP` with `snp=ss$rsID` or whatever the rsID is called in ss.

**Comment by Mahantesh-Biradar** [comment]
Thanks again. 

1. for ref.bfile, I used the one provided with lassosum (ref.bfile <- "refpanel"). Please let me know if I need to change something for this. 
2. Let me try by matching with rsID.

**Comment by tshmak** [comment]
No wonder. "refpanel" is a toy dataset provided only for the example. It is not meant to be used for real analysis. Just remove `ref.bfile=ref.bfile` from your command and it will just use test.bfile as your ref.bfile, and it should work.

**Comment by Mahantesh-Biradar** [comment]
Got it and it worked well. thanks
