### ISSUE TITLE
Error in validate.lassosum.pipeline(out) :    There's no variation in phenotype

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [tshmak/lassosum#41]
I have a binary outcome denoted by 1 and 2 in the .fam file of test data and I'm getting the following error when I tried to run validation step:

v <- validate(out) # Use the 6th column in .fam file in test dataset for test phenotype

Error:

Error in validate.lassosum.pipeline(out) : 
  There's no variation in phenotype
  
  Can you please suggest how to address this?
  
  PS: I have replaced missing values with NA instead of -9

**Comment by privefl** [comment]
Is there any variation in this column?
Or do you have the exact same value in all entries?

**Comment by Mahantesh-Biradar** [comment]
Yes, there is a varition. I have about 14K cases and 400K controls and few missing values indicated by NA.
