### ISSUE TITLE
pseudovalidate() with no LD

### ISSUE THREAD

**Issue by euffelmann** [tshmak/lassosum#45]
Does pseudovalidate() also provide a valid estimate of corr(PRS, Phenotype) when there is no LD? That is, I'm simulating SNP data with no LD, then run a GWAS of a disease phenotype using these SNPs. Using the resulting summary stats, and a test.bfile that also has no LD, will pseudovalidate provide a correct estimate?

**Comment by tshmak** [comment]
Not sure why you want to use pseudovalidate rather than simply correlating the generated phenotype with PRS. In general, pseudovalidation is deprecated in favour of splitvalidation. See the README.md for more details.

**Comment by euffelmann** [comment]
Sorry, above I meant I use ref.bfile without LD. So I would like to use lassosum to get an estimate of R2 from the summary statistics and and a reference sample alone (no test data). As I understand, for this I can use pseudovalidate. splitvalidation requires a test.bfile.

**Comment by tshmak** [comment]
In general, pseudovalidation is not very robust. It's based on a heuristic and its performance on real life datasets is unknown. Hence, I don't recommend it in general. I also don't know what's the impact of LD (or the lack thereof) has on it.

**Comment by euffelmann** [comment]
That's also the feeling I got from my simulations. Thank you!
