### ISSUE TITLE
pseudovalidation double destandardize

### ISSUE THREAD

**Issue by JasmRicard** [tshmak/lassosum#46]
When using function pseudovalidate.lassosum.pipeline.R with `destandardize=T`, betas are destandardized and given to function pseudovalidation.R where they are destandardized again to compute bXXb. I was wondering what explains the need a such a double destandardization? I understand that this is not the case if one specifies `destandardize=F` in the first function. Still, if one wishes to obtain pgs computed on destandardized betas, `destandardize=T` needs to be specified.

Many thanks for the clarification,
Jasmin

**Comment by tshmak** [comment]
The `destandardize` argument is probably not supposed to be used with `pseudovalidate`. In any case, pseudovalidation is deprecated. One should use splitvalidate or simply validate instead.

**Comment by JasmRicard** [comment]
If I understand well, you now discourage the use of pseudovalidation as presentend in the original Lassosum paper?

**Comment by tshmak** [comment]
Correct. I also made similar comments in another thread: https://github.com/tshmak/lassosum/issues/45

**Comment by JasmRicard** [comment]
Many thanks for the clarification.
