### ISSUE TITLE
Getting predicted phenotypes from validate()

### ISSUE THREAD

**Issue by linkeli0412** [tshmak/lassosum#48]
Hi!

Thank you for your help on crosspred thread, I think this is more lassosum related so I will just put it here.

Is there a way to obtain the predicted phenotypes from the PGS and use them to calculate the specifcity, sensitivity and balanced accuracy for model comparison? I figured the pheno in result.table is the true phenotype we input for the test dataset.

Thank you for the help

**Comment by tshmak** [comment]
No, the model you use to predict the pheno type is beyond the scope of lassosum, so you should fit the model yourself.
