### ISSUE TITLE
Gaps and overlaps between LD regions of Berisa.XXX.hg38.bed files

### ISSUE THREAD

**Issue by ilarsf** [tshmak/lassosum#9]
Dear Timothy,

Thanks for and congratulations to your hard work on lassosum!
Some of the LD regions of the provided Berisa.XXX.hg38.bed files overlap. Also, there are gaps between the regions. However, they were no overlaps and no gaps in the original Berisa.XXX.hg19.bed files.

Berisa.EUR.**hg38**.bed:
`        chr      pos     pos2`
`   1:  chr1    10583  1892607`
`   2:  chr1  1961168  3666172`
`   3:  chr1  3582736  4380811`
`   4:  chr1  4320751  5853833`
`   5:  chr1  5853833  7187275`
Overlap: line 2 ends at 3,666,172, line 3 starts at 3,582,736
Gap: line 2 ends at 1,892,607, line 3 starts at 1,961,168

Berisa.EUR.**hg19**.bed:
`        chr    start     stop`
`   1:  chr1    10583  1892607`
`   2:  chr1  1892607  3582736`
`   3:  chr1  3582736  4380811`
`   4:  chr1  4380811  5913893`
`   5:  chr1  5913893  7247335`

Any suggestions on how to resolve this?

Thanks,
Lars

**Comment by tshmak** [comment]
My bad. I simply used [liftover](https://genome.sph.umich.edu/wiki/LiftOver) to port the coordinates from hg19 to hg38, and did not check whether this introduced gaps. I suppose I should redo it making sure the end position and the start position of the next LD block is exactly the same. However, I am away from work at the moment. You can do the conversion using liftover yourself if you have time. Or alternatively, for a quick run, I suggest simply using Berisa.hg19. In my experience it actually doesn't affect the performance a lot.

**Comment by tshmak** [comment]
Hi Lars, 
I've updated the LD regions for hg38 in the latest release (v0.4.3). Please download and test. 
Thanks, 
Tim

**Comment by ilarsf** [comment]
Hi Tim,

Thank you very much for updating the LD regions. I have downloaded the latest release and will test it.

Best wishes,
Lars
